package com.ecommerce.analytics;

import com.ecommerce.model.Order;
import com.ecommerce.model.OrderItem;
import com.ecommerce.model.OrderStatus;
import com.ecommerce.model.PaymentType;
import com.ecommerce.model.Product;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Provides analytics operations for completed e-commerce orders.
 *
 * <p>Analytics calculations consider only orders whose status is
 * {@link OrderStatus#PAID}. Java Streams are used to filter, aggregate,
 * group, sort, and analyze order data.</p>
 */
public final class AnalyticsService {

    /**
     * Calculates the total revenue generated by paid orders.
     *
     * @param orders orders to analyze
     * @return total revenue from paid orders
     * @throws IllegalArgumentException if the orders list is null
     */
    public double calculateTotalRevenue(List<Order> orders) {

        if (orders == null) {
            throw new IllegalArgumentException(
                    "Orders cannot be null"
            );
        }

        return orders.stream()
                .filter(order -> order.getStatus() == OrderStatus.PAID)
                .mapToDouble(Order::calculateTotal)
                .sum();
    }

    /**
     * Calculates the average value of all paid orders.
     *
     * <p>If there are no paid orders, the method returns {@code 0.0}.</p>
     *
     * @param orders orders to analyze
     * @return average value of paid orders, or 0.0 if none exist
     * @throws IllegalArgumentException if the orders list is null
     */
    public double calculateAverageOrderValue(List<Order> orders) {

        if (orders == null) {
            throw new IllegalArgumentException(
                    "Orders cannot be null"
            );
        }

        return orders.stream()
                .filter(order -> order.getStatus() == OrderStatus.PAID)
                .mapToDouble(Order::calculateTotal)
                .average()
                .orElse(0.0);
    }

    /**
     * Counts the number of paid orders.
     *
     * @param orders orders to analyze
     * @return number of orders with PAID status
     * @throws IllegalArgumentException if the orders list is null
     */
    public long countPaidOrders(List<Order> orders) {

        if (orders == null) {
            throw new IllegalArgumentException(
                    "Orders cannot be null"
            );
        }

        return orders.stream()
                .filter(order -> order.getStatus() == OrderStatus.PAID)
                .count();
    }

    /**
     * Counts paid orders grouped by payment type.
     *
     * <p>The returned map associates each payment type with the number
     * of paid orders that used that payment method.</p>
     *
     * @param orders orders to analyze
     * @return map of payment types to paid-order counts
     * @throws IllegalArgumentException if the orders list is null
     */
    public Map<PaymentType, Long> countOrdersByPaymentType(
            List<Order> orders) {

        if (orders == null) {
            throw new IllegalArgumentException(
                    "Orders cannot be null"
            );
        }

        return orders.stream()
                .filter(order -> order.getStatus() == OrderStatus.PAID)
                .collect(
                        Collectors.groupingBy(
                                Order::getPaymentType,
                                Collectors.counting()
                        )
                );
    }

    /**
     * Finds the product with the highest total quantity sold
     * across all paid orders.
     *
     * <p>An {@link Optional} is returned because no best-selling product
     * exists when there are no qualifying order items.</p>
     *
     * @param orders orders to analyze
     * @return best-selling product, or an empty Optional if none exists
     * @throws IllegalArgumentException if the orders list is null
     */
    public Optional<Product> findBestSellingProduct(
            List<Order> orders) {

        if (orders == null) {
            throw new IllegalArgumentException(
                    "Orders cannot be null"
            );
        }

        return orders.stream()
                .filter(order -> order.getStatus() == OrderStatus.PAID)
                .flatMap(order -> order.getItems().stream())
                .collect(
                        Collectors.groupingBy(
                                OrderItem::getProduct,
                                Collectors.summingInt(
                                        OrderItem::getQuantity
                                )
                        )
                )
                .entrySet()
                .stream()
                .max(Map.Entry.comparingByValue())
                .map(Map.Entry::getKey);
    }

    /**
     * Calculates revenue generated by each product category
     * across all paid orders.
     *
     * @param orders orders to analyze
     * @return map containing category names and their generated revenue
     * @throws IllegalArgumentException if the orders list is null
     */
    public Map<String, Double> calculateRevenueByCategory(
            List<Order> orders) {

        if (orders == null) {
            throw new IllegalArgumentException(
                    "Orders cannot be null"
            );
        }

        return orders.stream()
                .filter(order -> order.getStatus() == OrderStatus.PAID)
                .flatMap(order -> order.getItems().stream())
                .collect(
                        Collectors.groupingBy(
                                item -> item.getProduct().getCategory(),
                                Collectors.summingDouble(
                                        OrderItem::getSubtotal
                                )
                        )
                );
    }

    /**
     * Returns the highest-value paid orders sorted by total value
     * in descending order.
     *
     * @param orders orders to analyze
     * @param limit maximum number of orders to return
     * @return list of the highest-value paid orders
     * @throws IllegalArgumentException if the orders list is null
     *                                  or limit is not greater than zero
     */
    public List<Order> findTopPaidOrders(
            List<Order> orders,
            int limit) {

        if (orders == null) {
            throw new IllegalArgumentException(
                    "Orders cannot be null"
            );
        }

        if (limit <= 0) {
            throw new IllegalArgumentException(
                    "Limit must be greater than zero"
            );
        }

        return orders.stream()
                .filter(order -> order.getStatus() == OrderStatus.PAID)
                .sorted(
                        (order1, order2) ->
                                Double.compare(
                                        order2.calculateTotal(),
                                        order1.calculateTotal()
                                )
                )
                .limit(limit)
                .toList();
    }
}